language: node_js
sudo: required
dist: trusty
node_js: lts/*
cache:
  directories:
    - node_modules
git:
  depth: 1
before_install:
  - npm i -g npm@latest
install:
  - npm i
before_script:
  - npm run lint
script:
  - npm test
